// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmaPUzqKVawebJ8ajgUnNt_3hOOU_clg',
    appId: '1:199016142151:web:e350daffc106622384a862',
    messagingSenderId: '199016142151',
    projectId: 'appenem-69a1f',
    authDomain: 'appenem-69a1f.firebaseapp.com',
    databaseURL: 'https://appenem-69a1f-default-rtdb.firebaseio.com',
    storageBucket: 'appenem-69a1f.firebasestorage.app',
    measurementId: 'G-Z1T5WKDLEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6gDgjI3xhre9k4JuBr4CgFlkw-JLggg',
    appId: '1:199016142151:android:ea304d37dd6a71ce84a862',
    messagingSenderId: '199016142151',
    projectId: 'appenem-69a1f',
    databaseURL: 'https://appenem-69a1f-default-rtdb.firebaseio.com',
    storageBucket: 'appenem-69a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUe4UolYPwqksr-JMakaAG6rPZT72evKg',
    appId: '1:199016142151:ios:e2ce69bf6b95e6f584a862',
    messagingSenderId: '199016142151',
    projectId: 'appenem-69a1f',
    databaseURL: 'https://appenem-69a1f-default-rtdb.firebaseio.com',
    storageBucket: 'appenem-69a1f.firebasestorage.app',
    iosClientId: '199016142151-89vlqjvouqm0famevqijaegt5gkbjgib.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUe4UolYPwqksr-JMakaAG6rPZT72evKg',
    appId: '1:199016142151:ios:e2ce69bf6b95e6f584a862',
    messagingSenderId: '199016142151',
    projectId: 'appenem-69a1f',
    databaseURL: 'https://appenem-69a1f-default-rtdb.firebaseio.com',
    storageBucket: 'appenem-69a1f.firebasestorage.app',
    iosClientId: '199016142151-89vlqjvouqm0famevqijaegt5gkbjgib.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQmaPUzqKVawebJ8ajgUnNt_3hOOU_clg',
    appId: '1:199016142151:web:eff473013c8d74db84a862',
    messagingSenderId: '199016142151',
    projectId: 'appenem-69a1f',
    authDomain: 'appenem-69a1f.firebaseapp.com',
    databaseURL: 'https://appenem-69a1f-default-rtdb.firebaseio.com',
    storageBucket: 'appenem-69a1f.firebasestorage.app',
    measurementId: 'G-B9DWQF48FR',
  );
}
